### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by coree** [coree/ChiNet#1]
- [ ] ...

**Comment by niladell** [comment]
I'm pretty much in favor of the [CGAN](http://static.ijcai.org/proceedings-2017/0576.pdf) approach (or any other paper in the same line with better results (◔_◔)) and I agree with the general feeling of doing something nice and not going to hack the dataset. However, I found out that [tensor2tensor](https://github.com/tensorflow/tensor2tensor) has an implementation of the [_Attention Is All You Need_](https://arxiv.org/abs/1706.03762) transformer ([here](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py)). So, having that and knowing we do not have constrains on the libraries we can use maybe I'd give it a shot to try insert it in our model (although not making it an essential part). Despite that, it's probably wiser to first have a basic working thing, and after that divide the work on possible upgrade modules (like this one). 

If you guys want to check it out, there is an example implementation in a [Colab notebook](https://colab.research.google.com/notebook#fileId=/v2/external/notebooks/t2t/hello_t2t.ipynb) ,as well as in one of the Notebooks on the t2t repo.
