### ISSUE TITLE
Improving preprocessing given our current embedding 

### ISSUE THREAD

**Issue by niladell** [coree/ChiNet#17]
I just realized that we are doing an extremely naive preprocessing, especially with punctuation signs, numbers or composed (e.j. hyphened words). For sure this is something we should look into.

In the particular case of punctuation marks, we should be able to get rid of them without any big problem, given that we just have a set of short sentences. Also, we should probably convert all numbers to text; @coree you that are more familiar with it, any idea if NLTK, spaCy or similar libraries process this things directly? There are some words like "to" which I don't get at all why fail. Last thing are the names which, as I said, we are non-properly changing to an arbitrary string in the `dehumanizing`function and we should probably use real names.

This is an example of the current status when loading the word2vec embedding:

> 03/06 00:10 WARNING . not in embedding file
03/06 00:10 WARNING to not in embedding file
03/06 00:10 WARNING friendly_blorg_1 not in embedding file
03/06 00:10 WARNING a not in embedding file
03/06 00:10 WARNING and not in embedding file
03/06 00:10 WARNING , not in embedding file
03/06 00:10 WARNING of not in embedding file
03/06 00:10 WARNING 's not in embedding file
03/06 00:10 WARNING ! not in embedding file
03/06 00:10 WARNING friendly_blorg_2 not in embedding file
03/06 00:10 WARNING friendly_blorg_3 not in embedding file
03/06 00:10 WARNING 10 not in embedding file
03/06 00:10 WARNING ' not in embedding file
03/06 00:10 WARNING 20 not in embedding file
03/06 00:10 WARNING 100 not in embedding file
03/06 00:10 WARNING - not in embedding file
03/06 00:10 WARNING 30 not in embedding file
03/06 00:10 WARNING 50 not in embedding file
03/06 00:10 WARNING 15 not in embedding file
03/06 00:10 WARNING '' not in embedding file
03/06 00:10 WARNING `` not in embedding file
03/06 00:10 WARNING ? not in embedding file
03/06 00:10 WARNING 12 not in embedding file
03/06 00:10 WARNING cancelled not in embedding file
03/06 00:10 WARNING 18 not in embedding file
03/06 00:10 WARNING co-worker not in embedding file
03/06 00:10 WARNING 16 not in embedding file

**Comment by coree** [comment]
Getting rid of punctuation shouldn't be a problem. We can use RegexpTokinzer from nltk. To get rid of words like "to", we could use stop words. I didn't understand what you mean by "convert numbers to text", they are not already strings. But I'm not sure if we should remove all that either. Does this not contain valuable information about the text structure that a neural network cloud learns?

**Comment by niladell** [comment]
With numbers to text I mean this particular kind of error:
> 03/06 00:10 WARNING 10 not in embedding file

I haven't seen any written number (like "ten") in the error list, so maybe we'll fix that if we get _"10"_ and change it to _"ten"_. 

About the other things, I'm not sure either of what we should remove. I'm more in favour of having as much as information as possible, and getting rid of possesives, pronouns or other similar particles doesn't seem the best move. But I'm pretty clueless on how to approach it right now. As a first step, I think I'll change the current word2vec to Fasttext or a newer pretrained embedding, as they are probably better and have more vocabulary, but that's all I can think of.
